import type {CSSProperties} from 'react'

const mono = 'ui-monospace, SFMono-Regular, Menlo, Consolas, "Liberation Mono", monospace'

export const styles: Record<string, CSSProperties> = {
  page: {
    display: 'flex',
    flexDirection: 'column',
    height: '100vh',
    maxWidth: 900,
    margin: '0 auto',
    fontFamily: 'system-ui, sans-serif',
    color: '#1a1a1a',
  },
  header: {
    display: 'flex',
    alignItems: 'baseline',
    gap: 12,
    padding: '12px 16px',
    borderBottom: '1px solid #e5e5e5',
  },
  headerHint: {fontSize: 12, color: '#888'},

  messages: {
    flex: 1,
    overflowY: 'auto',
    padding: 16,
    display: 'flex',
    flexDirection: 'column',
    gap: 16,
  },
  empty: {color: '#888', fontSize: 14, lineHeight: 1.6},
  loading: {color: '#888', fontSize: 13, fontStyle: 'italic'},
  error: {
    color: '#b00',
    background: '#fdeaea',
    border: '1px solid #f3c2c2',
    borderRadius: 6,
    padding: '8px 12px',
    fontSize: 13,
  },

  message: {display: 'flex', flexDirection: 'column', gap: 6},
  roleUser: {fontSize: 11, fontWeight: 600, color: '#2563eb', textTransform: 'uppercase'},
  roleAssistant: {fontSize: 11, fontWeight: 600, color: '#16a34a', textTransform: 'uppercase'},
  text: {whiteSpace: 'pre-wrap', lineHeight: 1.6, fontSize: 14},

  reasoning: {fontSize: 12, color: '#666', background: '#fafafa', borderRadius: 6, padding: 8},

  tool: {
    border: '1px solid #e0e0e0',
    borderRadius: 8,
    background: '#fbfbfd',
    fontSize: 12,
  },
  toolSummary: {
    cursor: 'pointer',
    padding: '6px 10px',
    display: 'flex',
    alignItems: 'center',
    gap: 8,
  },
  toolState: {marginLeft: 'auto', color: '#999', fontFamily: mono, fontSize: 11},
  toolBody: {padding: '0 10px 10px', display: 'flex', flexDirection: 'column', gap: 4},
  toolLabel: {
    fontSize: 10,
    fontWeight: 700,
    color: '#999',
    textTransform: 'uppercase',
    marginTop: 6,
  },

  pre: {
    margin: 0,
    padding: 8,
    background: '#f4f4f6',
    borderRadius: 6,
    fontFamily: mono,
    fontSize: 12,
    lineHeight: 1.5,
    overflowX: 'auto',
    whiteSpace: 'pre-wrap',
    wordBreak: 'break-word',
  },

  // Compact inline chip for a tool call (click to open the detail panel)
  toolChip: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    padding: '6px 10px',
    border: '1px solid #e0e0e0',
    borderRadius: 8,
    background: '#fbfbfd',
    fontSize: 12,
    cursor: 'pointer',
    textAlign: 'left',
    width: 'fit-content',
    maxWidth: '100%',
  },
  toolChipName: {fontWeight: 600},
  toolChipState: {color: '#999', fontFamily: mono, fontSize: 11},
  toolChipChevron: {color: '#bbb', marginLeft: 4},
  toolChipError: {color: '#b00', fontFamily: mono, fontSize: 11},

  // Slide-in detail panel
  panelBackdrop: {
    position: 'fixed',
    inset: 0,
    background: 'rgba(0,0,0,0.25)',
    zIndex: 100,
  },
  panel: {
    position: 'fixed',
    top: 0,
    right: 0,
    height: '100vh',
    width: 'min(560px, 92vw)',
    background: '#fff',
    boxShadow: '-4px 0 24px rgba(0,0,0,0.12)',
    zIndex: 101,
    display: 'flex',
    flexDirection: 'column',
  },
  panelHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: 10,
    padding: '14px 16px',
    borderBottom: '1px solid #e5e5e5',
  },
  panelTitle: {fontWeight: 600, fontSize: 14, fontFamily: mono},
  panelClose: {
    marginLeft: 'auto',
    border: 'none',
    background: 'transparent',
    fontSize: 18,
    lineHeight: 1,
    cursor: 'pointer',
    color: '#666',
    padding: 4,
  },
  panelBody: {
    flex: 1,
    overflowY: 'auto',
    padding: 16,
    display: 'flex',
    flexDirection: 'column',
    gap: 8,
  },
  // The input tree gets generous vertical room so it isn't squeezed to a
  // sliver by a large output; it scrolls internally past that height.
  panelInput: {
    maxHeight: '38vh',
    overflowY: 'auto',
    flexShrink: 0,
  },

  // Tool definition card (in the tools inspector) — an accordion row
  toolDef: {
    border: '1px solid #e5e5e5',
    borderRadius: 8,
    overflow: 'hidden',
  },
  toolRowHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    width: '100%',
    padding: '10px 12px',
    border: 'none',
    background: 'transparent',
    cursor: 'pointer',
    textAlign: 'left',
  },
  toolRowPreview: {
    flex: 1,
    minWidth: 0,
    fontSize: 12,
    color: '#888',
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
  },
  toolRowBody: {
    padding: '0 12px 12px',
    display: 'flex',
    flexDirection: 'column',
    gap: 4,
    borderTop: '1px solid #f0f0f0',
  },
  toolDefName: {fontFamily: mono, fontSize: 13, fontWeight: 700, color: '#1a1a1a'},
  descDetails: {fontSize: 12},
  descSummary: {cursor: 'pointer', color: '#2563eb', fontSize: 12, padding: '2px 0'},
  descPre: {
    margin: '6px 0 0',
    padding: 10,
    background: '#f4f4f6',
    borderRadius: 6,
    fontFamily: mono,
    fontSize: 12,
    lineHeight: 1.5,
    whiteSpace: 'pre-wrap',
    wordBreak: 'break-word',
    maxHeight: 320,
    overflowY: 'auto',
  },

  // Small header button (e.g. "Tools")
  headerButton: {
    marginLeft: 'auto',
    padding: '5px 12px',
    fontSize: 12,
    fontWeight: 600,
    color: '#1a1a1a',
    background: '#fff',
    border: '1px solid #ccc',
    borderRadius: 7,
    cursor: 'pointer',
  },

  // JSON tree
  treeWrap: {
    fontFamily: mono,
    fontSize: 12,
    lineHeight: 1.55,
    background: '#f4f4f6',
    borderRadius: 6,
    padding: 8,
    overflowX: 'auto',
  },
  treeToggle: {
    cursor: 'pointer',
    userSelect: 'none',
    color: '#888',
    display: 'inline-block',
    width: 14,
  },
  treeKey: {color: '#6f42c1'},
  treePunct: {color: '#999'},
  treeString: {color: '#0a7d33', whiteSpace: 'pre-wrap', wordBreak: 'break-word'},
  treeNumber: {color: '#1c6fd6'},
  treeBool: {color: '#b5560d'},
  treeNull: {color: '#999'},
  treeMuted: {color: '#aaa', fontStyle: 'italic'},

  inputRow: {display: 'flex', gap: 8, padding: 16, borderTop: '1px solid #e5e5e5'},
  input: {
    flex: 1,
    padding: '10px 12px',
    fontSize: 14,
    border: '1px solid #ccc',
    borderRadius: 8,
    outline: 'none',
  },
  button: {
    padding: '10px 18px',
    fontSize: 14,
    fontWeight: 600,
    color: '#fff',
    background: '#1a1a1a',
    border: 'none',
    borderRadius: 8,
    cursor: 'pointer',
  },
}
